#!/bin/sh

tpm='#tpm-luks
tpm_infineon
tpm_tis
tpm_atmel
tpm_nsc
#tpm-luks'


# remove tpm-luks section from /etc/modules
sed -i '/#tpm-luks/,/#tpm-luks/d' /etc/initramfs-tools/modules

echo "$tpm" >> /etc/initramfs-tools/modules


exit 0
