#!/bin/bash

DEVICE="/dev/sda"

function tpm_enabled
{
	if [ ! -e /sys/class/misc/tpm0/device/enabled ]; then
		echo "Your TPM device driver doesn't appear to be loaded. Please run"
		echo "\`modprobe tpm_tis\` to load the driver and re-run this script"
		exit 7
	fi

	if [ ! /sys/class/misc/tpm0/device/enabled ]; then
		echo "Your TPM is not enabled in your BIOS. Please halt the machine and"
		echo "then cold boot into your BIOS to enable the TPM chip."
		exit 8
	fi

	return 0
}

function tpm_owned
{
	if [ $(cat /sys/class/misc/tpm0/device/owned) -ne 1 ]; then
		echo "TPM is unowned, taking ownership.."
		tpm_takeownership -y -z || exit 9
	fi

	return 0
}

#check if tpm owner password is well known
function tpm_check_password
{
	tpm_changeownerauth -o -z -r
	if [ $? -ne 0 ]; then
		echo "TPM password is unknown. Please halt the machine and then cold boot into your BIOS and reset the TPM chip."
		exit 10
	fi

}

# install TrustedGRUB if PCR-12 is not extended
function check_trustedgrub_installed 
{

	if grep -q "PCR-12: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00" /sys/class/misc/tpm0/device/pcrs; then
		echo "Removing GRUB"
		apt-get -y remove grub* --purge &> /dev/null

		echo "Installing TrustedGRUB"
		apt-get -y install grub  &> /dev/null 

		grub-install $DEVICE --no-floppy &> /dev/null || (echo "grub-install failed" && exit 1)
	fi
}

function findLuksVolume
{

	PARTI_LIST=$(fdisk -l $DEVICE | grep ^\/dev | awk '{print $1}')
	echo $(for i in $PARTI_LIST; do if cryptsetup isLuks $i;then echo $i; fi; done)
}

function tpm_clear_nvram
{
	echo "Clearing NVRAM areas with index 1 to 10."
	echo -e "This ensures that enough space for LUKS secret is available.\n"

	read -p "Press [Enter] key to continue..."

	for i in $(seq 1 10); do
		tpm_nvrelease -y -i $i &> /dev/null
	done


	



}

function tpm_luks
{
	VOLUME=$(findLuksVolume)

	if [ -z $VOLUME ]; then
		echo "No encrypted LUKS volume found"
		exit 1
	fi
	
	echo "Store LUKS secret in TPM NVRAM"
	INDEX=$(tpm-luks -c -d $VOLUME | egrep -o '\([0-9]+\)' | tr -d '()')
	if [ $INDEX -gt 0 ]; then
		echo "Saving NVRAM index in /etc/tpm-luks.conf"
		echo "${VOLUME}:${INDEX}:/usr/sbin/tpm-luks-gen-tgrub-pcr-values" >/etc/tpm-luks.conf
		
		echo "Running update-initramfs"
		update-initramfs -u &> /dev/null
	
		echo "Running tpm-luks-update"
		tpm-luks-update -r -y || (echo "tpm-luks-update failed" && exit 1)
	fi
}

tpm_enabled
tpm_owned
tpm_check_password
tpm_clear_nvram
check_trustedgrub_installed 
tpm_luks
